// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package internal

import (
	"context"
)

const createDeviceType = `-- name: CreateDeviceType :exec
INSERT INTO device_type (name) VALUES ($1)
`

func (q *Queries) CreateDeviceType(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDeviceType)
	return err
}

const createManufacturer = `-- name: CreateManufacturer :exec
INSERT INTO manufacturer (name) VALUES ($1)
`

func (q *Queries) CreateManufacturer(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createManufacturer)
	return err
}

const deleteDeviceType = `-- name: DeleteDeviceType :exec
DELETE FROM device_type
WHERE id = $1
`

func (q *Queries) DeleteDeviceType(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceType)
	return err
}

const deleteManufacturer = `-- name: DeleteManufacturer :exec
DELETE FROM manufacturer
WHERE id = $1
`

func (q *Queries) DeleteManufacturer(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteManufacturer)
	return err
}

const getAllEquipment = `-- name: GetAllEquipment :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
`

// EQUIPMENT QUERIES
func (q *Queries) GetAllEquipment(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getAllEquipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTypeById = `-- name: GetDeviceTypeById :one
SELECT id, name, status FROM device_type
WHERE id = $1
ORDER BY id
`

func (q *Queries) GetDeviceTypeById(ctx context.Context) (DeviceType, error) {
	row := q.db.QueryRowContext(ctx, getDeviceTypeById)
	var i DeviceType
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getDeviceTypeByName = `-- name: GetDeviceTypeByName :one
SELECT id, name, status FROM device_type
WHERE name = $1
ORDER BY id
`

func (q *Queries) GetDeviceTypeByName(ctx context.Context) (DeviceType, error) {
	row := q.db.QueryRowContext(ctx, getDeviceTypeByName)
	var i DeviceType
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}

const getDeviceTypesActive = `-- name: GetDeviceTypesActive :many
SELECT id, name FROM device_type
WHERE status = 'active'
ORDER BY id
`

type GetDeviceTypesActiveRow struct {
	ID   int32
	Name string
}

// DEVICETYPE QUERIES
func (q *Queries) GetDeviceTypesActive(ctx context.Context) ([]GetDeviceTypesActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceTypesActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceTypesActiveRow
	for rows.Next() {
		var i GetDeviceTypesActiveRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentByDeviceType = `-- name: GetEquipmentByDeviceType :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE device_type_id = $1
`

func (q *Queries) GetEquipmentByDeviceType(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentByDeviceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentByDeviceTypeAndManufacturer = `-- name: GetEquipmentByDeviceTypeAndManufacturer :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE device_type_id = $1 AND manufacturer_id = $2
`

func (q *Queries) GetEquipmentByDeviceTypeAndManufacturer(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentByDeviceTypeAndManufacturer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentByDeviceTypeAndSerialNumber = `-- name: GetEquipmentByDeviceTypeAndSerialNumber :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE device_type_id = $1 AND serial_number = $2
`

func (q *Queries) GetEquipmentByDeviceTypeAndSerialNumber(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentByDeviceTypeAndSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentByDeviceTypeManufacturerAndSerialNumber = `-- name: GetEquipmentByDeviceTypeManufacturerAndSerialNumber :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE device_type_id = $1 AND manufacturer_id = $2 AND serial_number = $3
`

func (q *Queries) GetEquipmentByDeviceTypeManufacturerAndSerialNumber(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentByDeviceTypeManufacturerAndSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentByManufacturer = `-- name: GetEquipmentByManufacturer :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE manufacturer_id = $1
`

func (q *Queries) GetEquipmentByManufacturer(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentByManufacturer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentByManufacturerAndSerialNumber = `-- name: GetEquipmentByManufacturerAndSerialNumber :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE manufacturer_id = $1 AND serial_number = $2
`

func (q *Queries) GetEquipmentByManufacturerAndSerialNumber(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentByManufacturerAndSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEquipmentBySerialNumber = `-- name: GetEquipmentBySerialNumber :one
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE serial_number = $1
`

func (q *Queries) GetEquipmentBySerialNumber(ctx context.Context) (SerialNumber, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentBySerialNumber)
	var i SerialNumber
	err := row.Scan(
		&i.AutoID,
		&i.DeviceTypeID,
		&i.ManufacturerID,
		&i.SerialNumber,
	)
	return i, err
}

const getEquipmentLikeSerialNumber = `-- name: GetEquipmentLikeSerialNumber :many
SELECT auto_id, device_type_id, manufacturer_id, serial_number FROM serial_numbers
WHERE serial_number LIKE $1
`

func (q *Queries) GetEquipmentLikeSerialNumber(ctx context.Context) ([]SerialNumber, error) {
	rows, err := q.db.QueryContext(ctx, getEquipmentLikeSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SerialNumber
	for rows.Next() {
		var i SerialNumber
		if err := rows.Scan(
			&i.AutoID,
			&i.DeviceTypeID,
			&i.ManufacturerID,
			&i.SerialNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManufacturerById = `-- name: GetManufacturerById :one
SELECT id, name FROM manufacturer
WHERE id = $1
ORDER BY id
`

type GetManufacturerByIdRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetManufacturerById(ctx context.Context) (GetManufacturerByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getManufacturerById)
	var i GetManufacturerByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getManufacturerByName = `-- name: GetManufacturerByName :one
SELECT id, name FROM manufacturer
WHERE name = $1
ORDER BY id
`

type GetManufacturerByNameRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetManufacturerByName(ctx context.Context) (GetManufacturerByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getManufacturerByName)
	var i GetManufacturerByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getManufacturersActive = `-- name: GetManufacturersActive :many
SELECT id, name FROM manufacturer
WHERE status = 'active'
ORDER BY id
`

type GetManufacturersActiveRow struct {
	ID   int32
	Name string
}

// MANUFACTURER QUERIES
func (q *Queries) GetManufacturersActive(ctx context.Context) ([]GetManufacturersActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, getManufacturersActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetManufacturersActiveRow
	for rows.Next() {
		var i GetManufacturersActiveRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSerialNumberBySerialNumber = `-- name: GetSerialNumberBySerialNumber :one
SELECT serial_number FROM serial_numbers
WHERE serial_number = $1
`

func (q *Queries) GetSerialNumberBySerialNumber(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSerialNumberBySerialNumber)
	var serial_number string
	err := row.Scan(&serial_number)
	return serial_number, err
}

const getSerialNumberLikeSerialNumber = `-- name: GetSerialNumberLikeSerialNumber :many
SELECT serial_number FROM serial_numbers
WHERE serial_number LIKE $1
`

func (q *Queries) GetSerialNumberLikeSerialNumber(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSerialNumberLikeSerialNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var serial_number string
		if err := rows.Scan(&serial_number); err != nil {
			return nil, err
		}
		items = append(items, serial_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSerialNumbers = `-- name: GetSerialNumbers :many
SELECT serial_number FROM serial_numbers
`

// SERIALNUMBER QUERIES
func (q *Queries) GetSerialNumbers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSerialNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var serial_number string
		if err := rows.Scan(&serial_number); err != nil {
			return nil, err
		}
		items = append(items, serial_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceType = `-- name: UpdateDeviceType :exec
UPDATE device_type SET name = $1
WHERE id = $2
`

func (q *Queries) UpdateDeviceType(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateDeviceType)
	return err
}

const updateDeviceTypeStatus = `-- name: UpdateDeviceTypeStatus :exec
UPDATE device_type SET status = $1
WHERE id = $2
`

func (q *Queries) UpdateDeviceTypeStatus(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateDeviceTypeStatus)
	return err
}

const updateManufacturer = `-- name: UpdateManufacturer :exec
UPDATE manufacturer SET name = $1
WHERE id = $2
`

func (q *Queries) UpdateManufacturer(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateManufacturer)
	return err
}

const updateManufacturerStatus = `-- name: UpdateManufacturerStatus :exec
UPDATE manufacturer SET status = $1
WHERE id = $2
`

func (q *Queries) UpdateManufacturerStatus(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateManufacturerStatus)
	return err
}

const updateSerialNumber = `-- name: UpdateSerialNumber :exec
UPDATE serial_numbers SET serial_number = $1
WHERE serial_number = $2
`

func (q *Queries) UpdateSerialNumber(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateSerialNumber)
	return err
}
